### ISSUE TITLE
Add Mikrotik router synthesis definition

### ISSUE THREAD

**Issue by OscarDCorbalan** [newrelic-experimental/entity-synthesis-definitions#209]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

Hello, I want to add an entity definition Mikrotik routers (https://mikrotik.com), but have doubts on the best way of doing it.

## Desired Behavior

Either have a specific Mikrotik router entity type, or have them in a generic router type.

## Possible Solution

I see that there currently is an [EXT-ROUTER definition](https://github.com/newrelic-experimental/entity-synthesis-definitions/tree/main/definitions/ext-router), which code talks about _Kentik_ routers, but also has this comment
  - `# Leaving this ambiguous to allow future technical partners to use the same entity type with additional conditions`

Should I:

1. submit a new entity definition, 
2. or modify the EXT-ROUTER to synthesize also the data from the Mikrotik routers?

If answer is 2:

- How do I add a mikrotik condition to the [type definition](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/definitions/ext-router/definition.yml)?
- How do I modify these [summary metrics](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/definitions/ext-router/summary_metrics.yml) to pick the metrics starting with `mikrotik.`? For example, this is what we have for Kentik:
```yaml
 - cpuUtilization:
  title: CPU Utilization (%)
  unit: PERCENTAGE
  query:
    select: average(kentik.snmp.CPU)
    from: Metric
    where: "provider = 'kentik-router'"
    eventId: entity.guid
```
- How do I modify the [dashboards definition](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/definitions/ext-router/dashboard.json) to condiitonally use metric names `kentik.x.y` or `mikrotik.a.b`? FOr example:
```json
"nrqlQueries": [
  {
    "accountId": 0,
      "query": "FROM Metric SELECT average(kentik.snmp.CPU) FACET entity.name WHERE provider = 'kentik-router' TIMESERIES 5 MINUTES"
  }
],
```

## Additional context

The router's data is dumped via the Metrics API with a script that runs on the router itself (pretty much like an agent), found here https://github.com/OscarDCorbalan/mikrotik-newrelic. 

By impersonating userId `2848364`, you should see a dashboard `Mikrotik Router` in the EU region (one.eu.newrelic) that uses that data.

This the shape of the data that is sent:

```json
[
   {
      "common":{
         "attributes":{
            "mikrotik.currentfirmware":"6.48.2",
            "mikrotik.model":"RBD52G-5HacD2HnD",
            "mikrotik.serialnumber":"C6140C7EBEF8",
            "mikrotik.upgradefirmware":"6.48.2"
         },
         "timestamp":1620969329
      },
      "metrics":[
         {
            "name":"mikrotik.firewall.connection.established",
            "type":"gauge",
            "value":32
         },
         {
            "name":"mikrotik.firewall.connection.tcp",
            "type":"gauge",
            "value":32
         },
         {
            "name":"mikrotik.firewall.connection.udp",
            "type":"gauge",
            "value":11
         },
         {
            "name":"mikrotik.interface.ether1.fprxbps",
            "type":"gauge",
            "value":656
         },
         {
            "name":"mikrotik.interface.ether1.fptxbps",
            "type":"gauge",
            "value":2736
         },
         [ ... rest of interfaces' throughput data ...] 
         {
            "name":"mikrotik.ip.dhcpserver.leases",
            "type":"gauge",
            "value":3
         },
         {
            "name":"mikrotik.ip.dns.cache.size",
            "type":"gauge",
            "value":1024
         },
         {
            "name":"mikrotik.ip.dns.cache.used",
            "type":"gauge",
            "value":589
         },
         {
            "name":"mikrotik.ip.pool.used",
            "type":"gauge",
            "value":2
         },
         {
            "name":"mikrotik.system.cpu.load",
            "type":"gauge",
            "value":2
         },
         {
            "name":"mikrotik.system.memory.free",
            "type":"gauge",
            "value":80629760
         },
         {
            "name":"mikrotik.system.memory.total",
            "type":"gauge",
            "value":134217728
         }
      ]
   }
]
```

**Comment by naxhh** [comment]
👋  the answer will be two indeed. We try to group concepts regardless of origin.

You can check an example on [EXT-SERVICE](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/definitions/ext-service)

The TL;DR is to add a new rule in the definition that identifies data from mikrotik.


About dashboards you will need to provide one dashboard for mikrotik and one for kentik (the existing one)
See [some docs here](https://github.com/newrelic-experimental/entity-synthesis-definitions#dashboard-templates)

And the same for [summary](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/docs/summary_metrics.md#roll-up-entities) and [golden metrics](https://github.com/newrelic-experimental/entity-synthesis-definitions/blob/main/docs/golden_metrics.md#roll-up-entities).


Here is an example i have not thought a lot about  but for reference

```yaml
synthesis:
  rules:
   # Kentik source
    - name: device_name
    identifier: device_name
    encodeIdentifierInGUID: true
    conditions:
    - attribute: provider
      value: kentik-router
      tags:
        provider:
          entityTagName: instrumentation.provider

   # Mikrotik
    - name: "?" # i dont see a good name attribute. is serialnumber good enough? model?
    identifier: mikrotik.serialnumber
    encodeIdentifierInGUID: true
    conditions:
    - attribute: mikrotik.model
      tags:
        ?: # do we have an attribute value that would be unique for mikrotik? let's assume the value is mikrotik for the examples
          entityTagName: instrumentation.provider

dashboardTemplates:
  kentik-router:
    template: dashboard.json
  mikrotik:
    template: dashboard.json
```

An example of Summary metric, will be similar for GM:

```
cpuUtilization:
  title: CPU Utilization (%)
  unit: PERCENTAGE
  queries:
      kentik-router
        select: average(kentik.snmp.CPU)
        from: Metric
        where: "provider = 'kentik-router'"
        eventId: entity.guid
    mikrotik:
      select: average(mikrotik.system.cpu.load)
      from: Metric
      eventId: entity.guid
```
